# Generated by Django 5.0 on 2025-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='path',
        ),
        migrations.AddField(
            model_name='albums',
            name='new_path',
            field=models.CharField(default='~/pics/new/', max_length=255),
        ),
        migrations.AddField(
            model_name='albums',
            name='old_path',
            field=models.CharField(default='~/pics/old/', max_length=255),
        ),
    ]
