# Generated by Django 5.0 on 2025-05-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_albums_path_albums_new_path_albums_old_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
    ]
