# Generated by Django 5.0 on 2025-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_rename_albums_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='new_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
