# Generated by Django 5.0 on 2025-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_alter_album_new_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
