# Generated by Django 5.0 on 2025-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0006_userprofile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="file_count",
            field=models.IntegerField(default=0),
        ),
    ]
