# Generated by Django 5.0 on 2025-08-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0007_album_file_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="conversion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="is_converted",
            field=models.BooleanField(default=False),
        ),
    ]
