# Generated by Django 5.0 on 2025-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0008_album_conversion_date_album_is_converted"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="conversion_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("converting", "En cours de conversion"),
                    ("completed", "Converti"),
                    ("error", "Erreur"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
