# Generated by Django 5.0 on 2025-08-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0009_album_conversion_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="is_converted",
        ),
    ]
