# Generated by Django 5.0 on 2025-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0010_remove_album_is_converted"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="conversion_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="current_file_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="current_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
